[package]
name = "sanchaar"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/components", "crates/core"]

[workspace.dependencies]
iced = { git = "https://github.com/nrjais/iced", features = [
    "svg",
    "tokio",
    "web-colors",
    "image",
    "highlighter",
    "debug",
    "advanced",
    "lazy",
    "wgpu",
], branch = "editor" }
rfd = { version = "0.14.1", default-features = false, features = [
    "xdg-portal",
    "tokio",
] }
iced_core = { git = "https://github.com/nrjais/iced", features = [
    "advanced",
], branch = "editor" }
tokio = { version = "1.36", features = ["fs", "macros", "io-util"] }
strum = { version = "0.26", features = ["derive"] }
reqwest = { version = "0.12", features = ["stream", "multipart"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
toml_edit = "0.22"
anyhow = "1.0"
mime_guess = "2.0"
slotmap = "1.0.7"
humansize = "2.1.3"
directories = "5.0.1"
log = "0.4.21"
regex = "1.10.4"


[dependencies]
components = { path = "crates/components" }
core = { path = "crates/core" }
iced = { workspace = true }
tokio = { workspace = true }
strum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
slotmap = { workspace = true }
humansize = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
rfd = { workspace = true }
log = { workspace = true }

[profile.dev]
incremental = true

[profile.dev.package."*"]
opt-level = 3
