[package]
name = "sanchaar"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.0", features = [
    "svg",
    "tokio",
    "web-colors",
    "image",
    "highlighter",
    "debug",
    "advanced",
    "lazy",
] }
rfd = { version = "0.14.0", default-features = false, features = [
    "xdg-portal",
    "tokio",
] }
tokio = { version = "1.36.0", features = ["fs", "macros"] }
iced_aw = { path = "../iced_aw", features = [
    "tabs",
    "split",
    "segmented_button",
    "icons",
    "spinner"
] }
strum = { version = "0.26.1", features = ["derive"] }
reqwest = { version = "0.11.6", features = ["stream"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
anyhow = "1.0.80"
mime_guess = "2.0.4"
slotmap = "1.0.7"

[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
iced = { path = "../iced" }
iced_aw = { path = "../iced_aw" }

