[package]
name = "Sanchaar"

[workspace.package]
authors = ["Neeraj Jaiswal <me@nrjais.com>"]
description = "A fast offline REST API Client"
version = "0.1.0-prerelease.1"
edition = "2021"

[workspace]
members = ["crates/*"]
default-members = ["crates/app"]

[workspace.dependencies]
iced = { git = "https://github.com/nrjais/iced", features = [
    "tokio",
    "web-colors",
    "highlighter",
    "debug",
    "advanced",
    "lazy",
    "wgpu",
], branch = "editor" }
iced_core = { git = "https://github.com/nrjais/iced", features = [
    "advanced",
], branch = "editor" }
rfd = { version = "0.14.1", default-features = false, features = [
    "xdg-portal",
    "tokio",
] }
tokio = { version = "1.36", features = ["fs", "macros", "io-util"] }
strum = { version = "0.26", features = ["derive"] }
reqwest = { version = "0.12", features = ["stream", "multipart"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
mime_guess = "2.0"
slotmap = "1.0.7"
humansize = "2.1.3"
directories = "5.0.1"
log = "0.4.21"
regex = "1.10.4"
hcl-rs = "0.18.0"
components = { path = "crates/components" }
core = { path = "crates/core" }

[[bin]]
name = "sanchaar"
path = "crates/app/src/main.rs"

[[bin]]
name = "sanchaar-cli"
path = "crates/cli/src/main.rs"

[profile.dev]
incremental = true

[profile.dev.package."*"]
opt-level = 3
