[package]
name = "Sanchaar"
description = "A fast offline REST API Client"
version = "0.1.0-prerelease.1"
edition = "2021"
repository = "https://github.com/nrjais/sanchaar"
authors = ["Neeraj Jaiswal <me@nrjais.com>"]

[package.metadata.bundle]
name = "Sanchaar"
identifier = "com.nrjais.sanchaar"
icon = [
    "assets/16x16.png",
    "assets/16x16@2x.png",
    "assets/32x32.png",
    "assets/32x32@2x.png",
    "assets/64x64.png",
    "assets/64x64@2x.png",
    "assets/128x128.png",
    "assets/128x128@2x.png",
    "assets/256x256.png",
    "assets/256x256@2x.png",
    "assets/512x512.png",
    "assets/512x512@2x.png",
]

[package.metadata.wix]
upgrade-guid = "2C50FBFA-6F0A-4713-A809-402C092E112B"
path-guid = "9B08627A-B062-486E-8CB9-0B767C1D7E8F"
license = false
eula = false

[workspace]
members = ["crates/components", "crates/core"]

[workspace.dependencies]
iced = { git = "https://github.com/nrjais/iced", features = [
    "tokio",
    "web-colors",
    "highlighter",
    "debug",
    "advanced",
    "lazy",
    "wgpu",
], branch = "editor" }
rfd = { version = "0.14.1", default-features = false, features = [
    "xdg-portal",
    "tokio",
] }
iced_core = { git = "https://github.com/nrjais/iced", features = [
    "advanced",
], branch = "editor" }
tokio = { version = "1.36", features = ["fs", "macros", "io-util"] }
strum = { version = "0.26", features = ["derive"] }
reqwest = { version = "0.12", features = ["stream", "multipart"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
toml_edit = "0.22"
anyhow = "1.0"
mime_guess = "2.0"
slotmap = "1.0.7"
humansize = "2.1.3"
directories = "5.0.1"
log = "0.4.21"
regex = "1.10.4"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.14.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Publish jobs to run in CI
pr-run-mode = "skip"
# Whether to install an updater program
install-updater = true


[dependencies]
components = { path = "crates/components" }
core = { path = "crates/core" }
iced = { workspace = true }
tokio = { workspace = true }
strum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
slotmap = { workspace = true }
humansize = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
rfd = { workspace = true }
log = { workspace = true }

[profile.dev]
incremental = true

[profile.dev.package."*"]
opt-level = 3

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
