cargo-features = ["codegen-backend"]

[package]
name = "sanchaar"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { path = "../iced", features = [
    "svg",
    "tokio",
    "web-colors",
    "image",
    "highlighter",
    "debug",
    "advanced",
    "lazy",
    "wgpu"
] }
#rfd = { version = "0.14.0", default-features = false, features = [
#    "xdg-portal",
#    "tokio",
#] }
tokio = { version = "1.36", features = ["fs", "macros"] }
strum = { version = "0.26.1", features = ["derive"] }
reqwest = { version = "0.12", features = ["stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.114"
toml = "0.8"
toml_edit = "0.22"
anyhow = "1.0"
mime_guess = "2.0.4"
slotmap = "1.0.7"
humansize = "2.1.3"
walkdir = "2.5"

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package."sanchaar"]
codegen-backend = "cranelift"

[patch.crates-io]
iced = { path = "../iced" }
