[package]
name = "js"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
# reqwest = { workspace = true }
rustyscript = { git = "https://github.com/nrjais/rustyscript", rev = "95d7194f835bddc33a45567ca5004536c8bf839d", features = [
  "url",
  "crypto",
  "url_import",
  "console",
  "deno_fetch",
] }
