description = "Http request"
version = "V1"

[http]
method = "GET"
url = "https://echo.nrjais.com"

[[http.headers]]
name = "header"
value = "sample"


[[http.headers]]
name = "header-another"
value = "sample"
disabled = true

[[http.query]]
name = "param"
value = "first"

[[http.query]]
name = "param"
value = "duplicate"

[[http.query]]
name = "another"
value = "second"
disabled = true

[http.body]
json = """
{
\"test\": \"hello\"
}
"""
