description = "Http request"
version = "V1"

[http]
method = "GET"
url = """
https://echo.nrjais.com
"""

[[http.headers]]
name = "header"
value = "sample"

[[http.query]]
name = "param"
value = "first"

[[http.query]]
name = "another"
value = "second"

[http.body]
Json = """
{
\"test\": \"hello\"
}
"""
