[package]
name = "sanchaar-cli"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[[bin]]
name = "sanchaar-cli"
path = "cli.rs"

[dependencies]
cli = { path = "../../crates/cli" }
