[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
js = { path = "../js" }
iced = { workspace = true }
slotmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
toml_edit = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
directories = { workspace = true }
reqwest = { workspace = true }
mime_guess = { workspace = true }
strum = { workspace = true }
regex = { workspace = true }
